---
title: "Conversation Rates from Control and Treatment Groups"
author: "Jie Huang, Mustafa Barez"
date: "21/03/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
install.packages ("pwr")
library(tidyverse)
library(ggplot2)
library (pwr)
```

```{r}
result_data <- read.csv("AB_testing.csv") 
result_data
```

```{r}
control_group <- result_data %>% filter( group == "control" & landing_page == "old_page")
treatment_group <- result_data %>% filter( group == "treatment" & landing_page == "new_page")
total <- rbind(control_group, treatment_group)
total
```

```{r}
table <- table(total$group,total$converted)
table
```

```{r}
prop.test(c (17489,17264), c (145274, 145311))
```

```{r}
barplot(table,legend = T,main = "Counts of Conversion Action from Two Groups")
```
```{r}
CHI = chisq.test(table, correct = T)
CHI
```
```{r}
CHI$expected
```
```{r}
fisher.test(table,conf.int = T, conf.level = 0.99)
```


```{r}
counts <- c(17489,17264)
barplot(counts,names.arg = c("Control", "Treatment"),main = "Counts of Conversions", col= 'green')
```
